<?php

return [
    'user_model' => env('CMS_CORE_USER_MODEL'),
    'super_admin_role' => env('CMS_CORE_SUPER_ADMIN_ROLE', 'core.super_admin'),
    'user_states' => ['active', 'inactive'],
    'users_per_page' => env('CMS_CORE_USERS_PER_PAGE', 15),

    'auth' => [
        'logout_redirect' => env('CMS_CORE_LOGOUT_REDIRECT', '/'),
    ],

    'admin_user' => [
        'name' => env('ADMIN_USER_NAME', 'Administrador'),
        'email' => env('ADMIN_USER_EMAIL'),
        'password' => env('ADMIN_USER_PASSWORD'),
    ],

    'site_options' => [
        'site_title' => env('CMS_SITE_TITLE', 'CMS PCTECK'),
        'site_description' => env('CMS_SITE_DESCRIPTION', 'Site institucional gerido pelo CMS PCTECK.'),
        'site_icon_url' => env('CMS_SITE_ICON_URL', '/vendor/cms-core/images/favicon.png'),
        'site_url' => env('CMS_SITE_URL', env('APP_URL', 'https://cliente.exemplo.pt')),
        'admin_email' => env('CMS_ADMIN_EMAIL', 'admin@exemplo.pt'),
        'locale' => env('CMS_SITE_LOCALE', 'pt_PT'),
        'smtp_enabled' => env('CMS_SMTP_ENABLED', false),
        'smtp_host' => env('MAIL_HOST', '127.0.0.1'),
        'smtp_port' => env('MAIL_PORT', 2525),
        'smtp_username' => env('MAIL_USERNAME'),
        'smtp_password' => env('MAIL_PASSWORD'),
        'smtp_encryption' => env('CMS_SMTP_ENCRYPTION', env('MAIL_ENCRYPTION')),
        'smtp_from_address' => env('MAIL_FROM_ADDRESS', env('CMS_ADMIN_EMAIL', 'admin@exemplo.pt')),
        'smtp_from_name' => env('MAIL_FROM_NAME', env('APP_NAME', 'CMS PCTECK')),
        'footer_enabled' => env('CMS_FOOTER_ENABLED', true),
        'footer_copyright_text' => env('CMS_FOOTER_COPYRIGHT_TEXT', 'Todos os direitos reservados'),
        'footer_background_color' => env('CMS_FOOTER_BACKGROUND_COLOR', '#0C0C0C'),
        'footer_text_color' => env('CMS_FOOTER_TEXT_COLOR', '#FFFFFF'),
        'footer_secondary_text_color' => env('CMS_FOOTER_SECONDARY_TEXT_COLOR', '#FFFFFF'),
        'footer_show_pcteckserv_credit' => env('CMS_FOOTER_SHOW_PCTECKSERV_CREDIT', true),
        'footer_credit_text' => env('CMS_FOOTER_CREDIT_TEXT', 'Desenvolvido por'),
        'footer_pcteckserv_logo_media_id' => env('CMS_FOOTER_PCTECKSERV_LOGO_MEDIA_ID'),
        'footer_pcteckserv_logo_path' => env('CMS_FOOTER_PCTECKSERV_LOGO_PATH', 'vendor/cms-core/images/logotipos-pcteckserv-texto.svg'),
        'footer_pcteckserv_logo_scale' => env('CMS_FOOTER_PCTECKSERV_LOGO_SCALE', 100),
        'footer_pcteckserv_url' => env('CMS_FOOTER_PCTECKSERV_URL', 'https://pcteckserv.com'),
        'footer_padding_y' => env('CMS_FOOTER_PADDING_Y', '28px'),
        'footer_padding_x' => env('CMS_FOOTER_PADDING_X', '24px'),
        'footer_max_width' => env('CMS_FOOTER_MAX_WIDTH', '1320px'),
        'maintenance_enabled' => env('CMS_MAINTENANCE_ENABLED', false),
        'maintenance_template' => env('CMS_MAINTENANCE_TEMPLATE', 'minimal'),
        'maintenance_show_logo' => env('CMS_MAINTENANCE_SHOW_LOGO', true),
        'maintenance_logo_media_id' => env('CMS_MAINTENANCE_LOGO_MEDIA_ID'),
        'maintenance_title' => env('CMS_MAINTENANCE_TITLE', 'Estamos a preparar algo novo.'),
        'maintenance_message' => env('CMS_MAINTENANCE_MESSAGE', 'O nosso site encontra-se temporariamente em manutenção. Voltamos em breve.'),
        'maintenance_secondary_text' => env('CMS_MAINTENANCE_SECONDARY_TEXT', 'Agradecemos a sua compreensão.'),
        'maintenance_schedule_enabled' => env('CMS_MAINTENANCE_SCHEDULE_ENABLED', false),
        'maintenance_start_at' => env('CMS_MAINTENANCE_START_AT'),
        'maintenance_end_at' => env('CMS_MAINTENANCE_END_AT'),
        'maintenance_auto_disable' => env('CMS_MAINTENANCE_AUTO_DISABLE', true),
        'maintenance_show_countdown' => env('CMS_MAINTENANCE_SHOW_COUNTDOWN', true),
        'maintenance_show_footer' => env('CMS_MAINTENANCE_SHOW_FOOTER', true),
        'maintenance_hero_media_id' => env('CMS_MAINTENANCE_HERO_MEDIA_ID'),
        'maintenance_background_color' => env('CMS_MAINTENANCE_BACKGROUND_COLOR', '#0C0C0C'),
        'maintenance_text_color' => env('CMS_MAINTENANCE_TEXT_COLOR', '#FFFFFF'),
        'maintenance_accent_color' => env('CMS_MAINTENANCE_ACCENT_COLOR', '#0D6EFD'),
        'maintenance_button_color' => env('CMS_MAINTENANCE_BUTTON_COLOR', '#0D6EFD'),
        'maintenance_access_enabled' => env('CMS_MAINTENANCE_ACCESS_ENABLED', false),
        'maintenance_access_code_hash' => env('CMS_MAINTENANCE_ACCESS_CODE_HASH'),
        'maintenance_access_version' => env('CMS_MAINTENANCE_ACCESS_VERSION', 1),
        'maintenance_access_duration' => env('CMS_MAINTENANCE_ACCESS_DURATION', '24h'),
        'maintenance_admin_bypass' => env('CMS_MAINTENANCE_ADMIN_BYPASS', true),
        'maintenance_allowed_ips' => env('CMS_MAINTENANCE_ALLOWED_IPS', ''),
        'maintenance_allowed_paths' => env('CMS_MAINTENANCE_ALLOWED_PATHS', ''),
        'maintenance_load_analytics' => env('CMS_MAINTENANCE_LOAD_ANALYTICS', false),
    ],

    'updates' => [
        'enabled' => env('CMS_UPDATER_ENABLED', true),
        'channel' => env('CMS_UPDATE_CHANNEL', 'stable'),
        'packages' => [
            'pcteckserv/cms-core',
        ],
        'repositories' => [
            'pcteckserv/cms-core' => env('CMS_CORE_REPOSITORY_URL', 'https://github.com/pcteckserv/cmspcteckserv-core.git'),
        ],
        'github_token' => env('CMS_GITHUB_TOKEN'),
    ],

    'media' => [
        'disk' => env('CMS_MEDIA_DISK', 'public'),
        'directory' => env('CMS_MEDIA_DIRECTORY', 'cms/media'),
        'max_size' => env('CMS_MEDIA_MAX_SIZE', 10 * 1024),
        'allow_svg' => env('CMS_MEDIA_ALLOW_SVG', false),
        'allowed_extensions' => ['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'pdf'],
        'allowed_mimes' => [
            'image/jpeg',
            'image/png',
            'image/webp',
            'image/gif',
            'image/svg+xml',
            'application/pdf',
        ],
        'optimization' => [
            'enabled' => env('CMS_MEDIA_OPTIMIZATION_ENABLED', true),
            'webp' => env('CMS_MEDIA_WEBP_ENABLED', true),
            'quality' => env('CMS_MEDIA_WEBP_QUALITY', 82),
            'keep_original' => env('CMS_MEDIA_KEEP_ORIGINAL', true),
            'variants' => [320, 640, 1280, 1920],
            'thumbnail' => [
                'width' => 300,
                'height' => 300,
            ],
        ],
        'size_warnings' => [
            'warning' => 500 * 1024,
            'critical' => 2 * 1024 * 1024,
        ],
        'resolution_warning' => [
            'width' => 2560,
            'height' => 1440,
        ],
        'permissions' => [
            'media.view',
            'media.upload',
            'media.upload-svg',
            'media.edit',
            'media.delete',
            'media.restore',
            'media.force-delete',
            'media.optimize',
        ],
    ],
];
